language: swift
os: osx
osx_image: xcode9.4

before_install:
  - git submodule update --init --recursive
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - ./bin/setup
  - xcodebuild -scheme SwiftBaas -workspace SwiftBaas.xcworkspace -sdk iphoneos